export const LINKEDIN_CONVERSION_IDS = {
  SCHEDULE: process.env.NEXT_PUBLIC_LINKEDIN_SCHEDULE_CONVERSION_ID || "",
  LEAD: process.env.NEXT_PUBLIC_LINKEDIN_LEAD_CONVERSION_ID || "",
  PURCHASE: process.env.NEXT_PUBLIC_LINKEDIN_PURCHASE_CONVERSION_ID || "",
  SIGNUP: process.env.NEXT_PUBLIC_LINKEDIN_SIGNUP_CONVERSION_ID || "",
};
